language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t javidaslan/react-app -f Dockerfile.dev .

script:
    - docker run -e CI=true javidaslan/react-app npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: "react-app"
    env: "ReactApp-env"
    bucket_name: elasticbeanstalk-us-east-2-582864530478
    bucket_path: "react-app"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY