language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t javidaslan/react-app -f Dockerfile.dev .


script:
    - docker run -e CI=true javidaslan/react-app npm run test -- --coverage